<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Version>3.3.7</Version>
    <AssemblyName>BazisSolverCP</AssemblyName>
    <SignAssembly>False</SignAssembly>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ChemTask.cs" />
    <Compile Remove="ElementData\ElementItem1DAxi.cs" />
    <Compile Remove="ElementData\ElementItem1DBeam.cs" />
    <Compile Remove="ElementData\ElementItem2DAxi.cs" />
    <Compile Remove="ElementData\ElementItem2DPlate.cs" />
    <Compile Remove="ElementData\ElementItem3D.cs" />
    <Compile Remove="ElementData\MechData.cs" />
    <Compile Remove="ElementData\TermalData.cs" />
    <Compile Remove="Extensions\DataTableEx.cs" />
    <Compile Remove="GeneralTask\GetUsedElemAndNodes.cs" />
    <Compile Remove="BoundaryConditions\IMechCalculator.cs" />
    <Compile Remove="BoundaryConditions\Mech1DCalculator.cs" />
    <Compile Remove="BoundaryConditions\Mech2DAxiCalculator.cs" />
    <Compile Remove="BoundaryConditions\Mech2DAxiCalculator_v2.cs" />
    <Compile Remove="BoundaryConditions\Mech2DPlaneCalculator.cs" />
    <Compile Remove="BoundaryConditions\Mech3DCalculator.cs" />
    <Compile Remove="MatrixSolvers\SmpRelaxationIterative.cs" />
    <Compile Remove="Matrix\ProfileNonSimMatrix.cs" />
    <Compile Remove="MechTask.cs" />
    <Compile Remove="MechTask\GlobalMatrixAssembly.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClientLogicCP" Version="1.1.10" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Project" Version="5.9.2" />
    <PackageReference Include="ResultDB" Version="1.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CAESolvers\CAESolvers.csproj" />
    <ProjectReference Include="..\PropertiesCalculator\PropertiesCalculator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="MechTask\" />
  </ItemGroup>

</Project>
