<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <PackageId>PropertiesCalculator</PackageId>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>PropertiesCalculator.snk</AssemblyOriginatorKeyFile>
    <DelaySign>False</DelaySign>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>Bilenko Georgy, Chaibrachmanov Radic</Authors>
    <Company>BAZIS SOFTWARE</Company>
    <Product>BAZIS</Product>
    <Description>Data base CRUD functrions for func and mat data</Description>
    <Copyright>Copyright © Bilenko Georgy 2023</Copyright>
    <PackageProjectUrl>https://www.bazisnet.ru/</PackageProjectUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <RootNamespace>PropertiesCalculator</RootNamespace>
    <AssemblyName>PropertiesCalculator</AssemblyName>
    <Version>1.1.2.0</Version>
    <AnalysisLevel>none</AnalysisLevel>
    <RunAnalyzersDuringBuild>True</RunAnalyzersDuringBuild>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <Platforms>AnyCPU;x86</Platforms>
        <!--Сохраняет пакет в указанной папке после сборки в зависимости от платформы-->
    <PackageOutputPath>c:\BazisComponents\IntPackages_v2\$(Configuration)</PackageOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net48|AnyCPU'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net48|x86'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="FunctionData\**" />
    <Compile Remove="Interfaces\**" />
    <Compile Remove="MaterialData\**" />
    <Compile Remove="Utilities\**" />
    <EmbeddedResource Remove="FunctionData\**" />
    <EmbeddedResource Remove="Interfaces\**" />
    <EmbeddedResource Remove="MaterialData\**" />
    <EmbeddedResource Remove="Utilities\**" />
    <None Remove="FunctionData\**" />
    <None Remove="Interfaces\**" />
    <None Remove="MaterialData\**" />
    <None Remove="Utilities\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="DataBaseInformer.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="icon.png" />
    <PackageReference Include="MaterialDB" Version="1.0.8" />
    <PackageReference Include="MathNet.Numerics.Signed" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </EmbeddedResource>
  </ItemGroup>
</Project>